### ISSUE TITLE
Archive mode doesn't work as expected

### ISSUE THREAD

**Issue by berfingit** [paulgb/Treeverse#21] opened 2018-08-27 13:37 UTC
Thank you for the Treeverse, it is very useful for us.
The issue is related to the archive mode.
If you open the archive mode from the Treeverse menu, the dragging area for the json files to be opened are not shown as in the screenshot-1.
![screenshot-1](https://user-images.githubusercontent.com/34516258/44662477-2e6d9e00-aa0e-11e8-9cae-d4c7a8dad772.png)
I tried to run the archive mode from this address also: https://paulgb.github.io/Treeverse/
In that case, I could upload the json file I have but the tweet contents are not visible in the graphical interface as in the screenshot-2.
![screenshot-2](https://user-images.githubusercontent.com/34516258/44662757-00d52480-aa0f-11e8-8842-1f9cb74e1b0c.jpg)
Therefore, in either case, we can't use the archive mode properly. 
Thanks again for all your effort.

**Comment by paulgb** [comment] 2018-09-04 11:07
Thanks for reporting this. Sorry for the slow reply as I've been away.

The archive button being broken on the extension is part of a bigger breakage that I'm tracking in #19, but the site that you linked to should still work. Is it possible for you to upload a twarc json file so that I can reproduce the issue?

**Comment by paulgb** [comment] 2018-09-30 17:04
Closing because this is being tracked in #19.

**Closed by paulgb** 2018-09-30 17:04 UTC
