### ISSUE TITLE
Seems to not work with the new twitter UI

### ISSUE THREAD

**Issue by domoritz** [paulgb/Treeverse#33] opened 2019-01-21 22:13 UTC
I'm having troubles using the extension with the new twitter UI. When I try your example, I just get an empty screen and the following errors in the js console. 

<img width="597" alt="screen shot 2019-01-21 at 14 12 06" src="https://user-images.githubusercontent.com/589034/51501423-b6ba5a00-1d86-11e9-99db-53fa7b241dd7.png">

**Comment by paulgb** [comment] 2019-01-21 22:58
Thanks for the report, I've confirmed it and am looking into it now.

**Comment by paulgb** [comment] 2019-01-22 02:48
I have the beginnings of this working in Chrome, but I haven’t pushed it to the app store yet because it would break things for the existing UI. My hope is that this is ready to go by the time Twitter moves everyone over to the new UI and then I won’t have to support the old UI any more.

To do:
- Test in Firefox
- Get the red dots (load more) to work
- Handle server-side cursors
- Clean up all the code that’s no longer necessary

**Comment by paulgb** [comment] 2019-02-03 00:38
The Chrome version for the new UI is published! It may take an hour or so to update.

Working on the FireFox version now.

**Comment by paulgb** [comment] 2019-02-03 01:19
Works in FireFox now too. Closing this and will open follow-up for remaining tasks.

**Closed by paulgb** 2019-02-03 01:19 UTC
